import {
  AnySQLiteColumn,
  integer,
  sqliteTable,
  text,
  unique,
} from "drizzle-orm/sqlite-core";
import { z } from "zod";
import {
  createInsertSchema,
  createSelectSchema,
  createUpdateSchema,
} from "drizzle-zod";

// =========================================
// BETTER AUTH SCHEMA
// Generated by Better Auth
// =========================================

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" }).notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const session = sqliteTable("session", {
  id: text("id").primaryKey(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
});

export const account = sqliteTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: integer("access_token_expires_at", {
    mode: "timestamp",
  }),
  refreshTokenExpiresAt: integer("refresh_token_expires_at", {
    mode: "timestamp",
  }),
  scope: text("scope"),
  password: text("password"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const verification = sqliteTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }),
  updatedAt: integer("updated_at", { mode: "timestamp" }),
});

// =========================================
// CUSTOM SCHEMA
// Application specific tables
// =========================================

export const folders = sqliteTable("folders", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  parentId: text("parent_id").references((): AnySQLiteColumn => folders.id), // Recursive
  ownerId: text("owner_id").notNull().references(() => user.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});

export const rules = sqliteTable("rules", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").notNull(),
  content: text("content").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  ownerId: text("owner_id").references(() => user.id),
  // Additional data (e.g. Cursor alwaysApply).
  metadata: text("metadata", { mode: "json" }),
  folderId: text("folder_id").references(() => folders.id),
}, (table) => [
  // Unique slug per user, but not globally.
  unique("user_scoped_unique_slug").on(table.ownerId, table.slug),
]);

export const SharePermission = {
  READ: 0b1,
  CLONE: 0b10,
  WRITE: 0b100,
} as const;

export const shares = sqliteTable("shares", {
  id: text("id").primaryKey(),
  token: text("token").notNull().unique(), // Public access key.
  name: text("name"), // Optional label for the shared collection.

  // Permissions are stored as a bitmask.
  permissions: integer("permissions").notNull().default(SharePermission.READ),

  ownerId: text("owner_id").notNull().references(() => user.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const shareItems = sqliteTable("share_items", {
  id: text("id").primaryKey(),
  shareId: text("share_id").notNull().references(() => shares.id, {
    onDelete: "cascade",
  }),

  // Link to either a rule or a folder.
  ruleId: text("rule_id").references(() => rules.id),
  folderId: text("folder_id").references(() => folders.id),
});

// =========================================
// ZOD SCHEMAS
// =========================================

// --- Rules ---
// TODO: Enhance metadata schema (for Cursor, Claude Code, etc.).
export const RuleSchema = createSelectSchema(rules, {
  metadata: z.any(),
});
export const RuleInsertSchema = createInsertSchema(rules, {
  metadata: z.any().optional(),
});
export const RuleUpdateSchema = createUpdateSchema(rules, {
  metadata: z.any().optional(),
});

export type Rule = z.infer<typeof RuleSchema>;
export type NewRule = z.infer<typeof RuleInsertSchema>;
export type RuleUpdate = z.infer<typeof RuleUpdateSchema>;

// --- Folders ---
export const FolderSchema = createSelectSchema(folders);
export const FolderInsertSchema = createInsertSchema(folders);
export const FolderUpdateSchema = createUpdateSchema(folders);

export type Folder = z.infer<typeof FolderSchema>;
export type NewFolder = z.infer<typeof FolderInsertSchema>;
export type FolderUpdate = z.infer<typeof FolderUpdateSchema>;

// --- Shares ---
export const ShareSchema = createSelectSchema(shares);
export const ShareInsertSchema = createInsertSchema(shares);
export const ShareUpdateSchema = createUpdateSchema(shares);

export type Share = z.infer<typeof ShareSchema>;
export type NewShare = z.infer<typeof ShareInsertSchema>;
export type ShareUpdate = z.infer<typeof ShareUpdateSchema>;

// --- Share Items ---
export const ShareItemSchema = createSelectSchema(shareItems);
export const ShareItemInsertSchema = createInsertSchema(shareItems);
export const ShareItemUpdateSchema = createUpdateSchema(shareItems);

export type ShareItem = z.infer<typeof ShareItemSchema>;
export type NewShareItem = z.infer<typeof ShareItemInsertSchema>;
export type ShareItemUpdate = z.infer<typeof ShareItemUpdateSchema>;
