import {
  FolderInsertSchema,
  FolderSchema,
  FolderUpdateSchema,
} from "@georules/database/schema";
import { z } from "zod";

/**
 * Input Schema for creating a folder.
 *
 * We omit:
 * - id: generated by backend.
 * - ownerId: derived from the authenticated session.
 * - createdAt: generated by DB.
 */
export const FolderCreateBodySchema = FolderInsertSchema.omit({
  id: true,
  ownerId: true,
  createdAt: true,
});

/**
 * Input Schema for updating a folder.
 *
 * We omit:
 * - id: immutable.
 * - ownerId: derived from the authenticated session.
 * - createdAt: immutable.
 */
export const FolderUpdateBodySchema = FolderUpdateSchema.omit({
  id: true,
  ownerId: true,
  createdAt: true,
});

/**
 * Output Schema for folder responses.
 */
export const FolderResponseSchema = FolderSchema.extend({}); // Get useful info on hover.

/**
 * Input Schema Type for creating a folder.
 *
 * We omit:
 * - id: generated by backend.
 * - ownerId: derived from the authenticated session.
 * - createdAt: generated by DB.
 */
export type FolderCreateBody = z.infer<typeof FolderCreateBodySchema>;

/**
 * Input Schema Type for updating a folder.
 *
 * We omit:
 * - id: immutable.
 * - ownerId: derived from the authenticated session.
 * - createdAt: immutable.
 */
export type FolderUpdateBody = z.infer<typeof FolderUpdateBodySchema>;

/**
 * Output Schema Type for folder responses.
 */
export type FolderResponse = z.infer<typeof FolderResponseSchema>;
