import {
  RuleInsertSchema,
  RuleSchema,
  RuleUpdateSchema,
} from "@georules/database/schema";
import { z } from "zod";

/**
 * Input Schema for creating a rule.
 *
 * We omit:
 * - id: generated by DB.
 * - ownerId: derived from the authenticated session.
 * - createdAt: generated by DB.
 */
export const RuleCreateBodySchema = RuleInsertSchema.omit({
  id: true,
  ownerId: true,
  createdAt: true,
});

/**
 * Input Schema for updating a rule.
 *
 * We omit:
 * - ownerId: derived from the authenticated session.
 */
export const RuleUpdateBodySchema = RuleUpdateSchema.omit({
  ownerId: true,
});

/**
 * Output Schema for rule responses.
 */
export const RuleResponseSchema = RuleSchema.extend({}); // Get useful info on hover.

/**
 * Input Schema Type for creating a rule.
 *
 * We omit:
 * - id: generated by DB.
 * - ownerId: derived from the authenticated session.
 * - createdAt: generated by DB.
 * - updatedAt: generated by DB.
 */
export type RuleCreateBody = z.infer<typeof RuleCreateBodySchema>;

/**
 * Input Schema Type for updating a rule.
 *
 * We omit:
 * - ownerId: derived from the authenticated session.
 */
export type RuleUpdateBody = z.infer<typeof RuleUpdateBodySchema>;

/**
 * Output Schema Type for rule responses.
 */
export type RuleResponse = z.infer<typeof RuleResponseSchema>;
